home:
  path: 'home'
  controller: HomeController
  action: index

article:
  path: 'article'
  controller: ArticleController
  action: index

article_new:
  path: 'article/new'
  controller: ArticleController
  action: new

404:
  path: '404'
  controller: ErrorController
  action: notFound